version: '3.6'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/code
    working_dir: /code
    env_file:
      - .env

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/code
    working_dir: /code
    command: celery -A app.celery worker -B --loglevel=INFO
    depends_on:
      - python
      - redis
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - "6379:6379"
